urls:
  #------------------------------------------------------------------
  - url:   https://www.sports.ru/tribuna/new.html
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/new.html
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/football/new.html
    parser: ru_sports_tribuna

  #------------------------------------------------------------------
