urls:
  #------------------------------------------------------------------
  - url:   http://www.sports.ru/tribuna/automoto/
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/new.html
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/f1/
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/f1/new.html
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/series/
    parser: ru_sports_tribuna

  - url:   http://www.sports.ru/tribuna/automoto/series/new.html
    parser: ru_sports_tribuna
  #------------------------------------------------------------------
